%YAML:1.0

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  model: calibrated
  time_offset: 0.0

  # accelerometer_noise_density: 6.0e-02  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  # accelerometer_random_walk: 8.0e-05    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  # gyroscope_noise_density: 5.0e-03     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  # gyroscope_random_walk: 3.0e-6      # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )

  accelerometer_noise_density: 1.5272e-03  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accelerometer_random_walk: 0.4800e-03    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyroscope_noise_density: 0.5398e-04     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyroscope_random_walk: 1.3374e-05      # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  rostopic: /imu/imu
  update_rate: 385.0

  # accelerometer_noise_density: 3.5272e-03  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  # accelerometer_random_walk: 2.4000e-03    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  # gyroscope_noise_density: 2.3980e-04    # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  # gyroscope_random_walk: 6.6660e-05     # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  # rostopic: /os1_cloud_node1/imu
  # update_rate: 100.0