%YAML:1.0

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]

  # great
  # accelerometer_noise_density: 4.89015e-3  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  # accelerometer_random_walk: 1.6301e-04    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  # gyroscope_noise_density: 2.9089e-04     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  # gyroscope_random_walk: 1.61604e-06       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )

  accelerometer_noise_density: 1.0000e-3  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accelerometer_random_walk: 1.5000e-3    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyroscope_noise_density: 1.0000e-04     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyroscope_random_walk: 1.0000e-05       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )

  # from kaist urban
  # accelerometer_noise_density: 5.8860e-02  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  # accelerometer_random_walk: 1.000e-03    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  # gyroscope_noise_density: 2.9089e-04     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  # gyroscope_random_walk: 1.0000e-04       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  
  # accelerometer_noise_density: 2.0000e-3  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  # accelerometer_random_walk: 3.0000e-3    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  # gyroscope_noise_density: 1.6968e-04     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  # gyroscope_random_walk: 1.9393e-05       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  model: calibrated
  rostopic: /imu0
  time_offset: 0.0
  update_rate: 100.0