%YAML:1.0

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  model: calibrated
  time_offset: 0.0

  # accelerometer_noise_density: 0.7000e-03  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  # accelerometer_random_walk: 1.4000e-03    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  # gyroscope_noise_density: 1.5e-04    # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  # gyroscope_random_walk: 1.0e-04     # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )

  accelerometer_noise_density: 0.7000e-03  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accelerometer_random_walk: 1.4000e-03    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyroscope_noise_density: 3.0e-04    # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyroscope_random_walk: 1.0e-04     # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )

  rostopic: /os_cloud_node/imu
  update_rate: 100.0